/**
 * constants.js
 * Master configuration constants, scene stages, camera coordinates,
 * portal definitions, pathogen datasets, outbreak policies, BioShield city config,
 * and Phase 8 Global Challenge Platform datasets.
 */

export const SCENE_STAGES = {
  LOADING: 1,
  CINEMATIC_INTRO: 2,
  ROCKET_LAUNCH: 3,
  SPACE_FLIGHT: 4,
  ORBITAL_STATION: 5,
  COMMAND_CENTER: 6,
  EARTH_VIEW: 7,
  TIME_TRAVEL: 8,
  HISTORICAL_MUSEUM: 9,
  SHRINK_TRANSITION: 10,
  HUMAN_BODY_JOURNEY: 11,
  AI_LABORATORY: 12,
  OUTBREAK_SIMULATOR: 13,
  MISSION_CONTROL: 14,
  BIOSHIELD_2050: 15,
  CHALLENGE_PLATFORM: 16,
  INTELLIGENCE_PLATFORM: 17,
};

/** Phase 8 Scenarios for Modules 2 & 9 */
export const CHALLENGE_SCENARIOS = [
  { id: 'plague',       name: '1. Historical Plague Response', category: 'History', icon: '🏛️', diff: 'Medium', desc: 'Contain a Yersinia pestis outbreak using medieval quarantine & early isolation protocols.' },
  { id: 'influenza',    name: '2. 1918 Flu Crisis Containment', category: 'Viral',   icon: '🫁', diff: 'Hard',   desc: 'Manage rapid airborne transmission during world wartime transport.' },
  { id: 'covid',        name: '3. Novel Coronavirus Surge',    category: 'Respiratory', icon: '🦠', diff: 'Hard', desc: 'Deploy mRNA vaccines, PCR testing, and ICU bed expansion during global surges.' },
  { id: 'hospital',     name: '4. Hospital Capacity Crisis',   category: 'Healthcare', icon: '🏥', diff: 'Medium', desc: 'Reallocate doctors, ventilators, and emergency funding to prevent ICU collapse.' },
  { id: 'vaccine',      name: '5. Global Vaccine Rollout',     category: 'Clinical',  icon: '💉', diff: 'Easy',   desc: 'Distribute 10 Billion vaccine doses across 6 continents overcoming logistics bottlenecks.' },
  { id: 'unknown',      name: '6. Unknown Pathogen X Investigation', category: 'Biosecurity', icon: '☣️', diff: 'Expert', desc: 'Isolate an unknown zoonotic pathogen using 3D protein slicing & AI diagnostic tools.' },
  { id: 'grand',        name: '7. FINAL GRAND CHALLENGE: BioShield Master', category: 'Grand Master', icon: '🏆', diff: 'Grand Master', desc: 'Complete 8-step comprehensive crisis response covering diagnosis, research, policy, and public health.' },
];

/** Phase 8 Educational Quiz Questions for Module 6 */
export const CHALLENGE_QUIZZES = [
  {
    id: 'q1',
    question: 'How do mRNA vaccines train the human immune system to fight viruses?',
    options: [
      'They inject live weakened virus particles into blood vessels.',
      'They provide mRNA instructions for cells to make a spike protein, triggering T-cell memory.',
      'They destroy white blood cells to make room for new antibodies.',
      'They permanently modify the patient’s nuclear DNA genome.'
    ],
    correct: 1,
    explanation: 'mRNA vaccines deliver synthetic mRNA wrapped in lipid nanoparticles that instruct host cells to produce harmless viral spike proteins. Ribosomes translate the mRNA and trigger robust T-cell and B-cell immune responses without live virus.'
  },
  {
    id: 'q2',
    question: 'What does the basic reproduction number R0 represent in epidemiology?',
    options: [
      'The percentage of hospital ICU beds currently occupied.',
      'The average number of secondary infections generated by one infected individual in a fully susceptible population.',
      'The number of days required to develop a new vaccine.',
      'The fatality rate per 100,000 infected individuals.'
    ],
    correct: 1,
    explanation: 'R0 (R-naught) indicates how contagious an infection is. If R0 = 3, each infected person spreads the disease to an average of 3 susceptible individuals.'
  },
  {
    id: 'q3',
    question: 'Which historical pandemic led to the first formal maritime quarantine systems in Europe?',
    options: [
      'The 1918 Spanish Influenza',
      'The 2009 Swine Flu Pandemic',
      'The Black Death (1347–1351)',
      'The 6th Cholera Pandemic'
    ],
    correct: 2,
    explanation: 'During the Black Death in 1377, the port city of Ragusa (Dubrovnik) instituted a 30-day isolation period ("trentino"), later expanded to 40 days ("quarentena", source of the word quarantine).'
  },
  {
    id: 'q4',
    question: 'Why is wastewater surveillance effective for early outbreak detection?',
    options: [
      'It measures air quality levels in high-density urban areas.',
      'Infected individuals shed viral RNA in stool days before developing clinical symptoms.',
      'It filters hospital oxygen supplies automatically.',
      'It predicts international flight arrivals in real-time.'
    ],
    correct: 1,
    explanation: 'Wastewater PCR monitoring detects shed viral fragments from asymptomatic and pre-symptomatic individuals up to 7 days before hospital admission spikes occur.'
  }
];

/** Phase 8 Achievements for Module 7 */
export const CHALLENGE_ACHIEVEMENTS = [
  { id: 'diseaseInvestigator', title: 'Disease Investigator', icon: '🔍', desc: 'Successfully identified Pathogen X transmission parameters.' },
  { id: 'researchScientist',  title: 'Research Scientist',   icon: '🔬', desc: 'Completed genomic sequencing and 3D molecular docking.' },
  { id: 'pandemicStrategist', title: 'Pandemic Strategist',  icon: '⚖️', desc: 'Enacted 16 emergency policy directives with zero economic collapse.' },
  { id: 'globalHealthLeader', title: 'Global Health Leader',  icon: '🌐', desc: 'Distributed 10 Billion vaccine doses across 6 continents.' },
  { id: 'bioshieldGuardian',  title: 'BioShield Guardian',   icon: '🛡️', desc: 'Mastered BioShield 2050 digital twin biosecurity operations.' },
];

/** Complete 8-Phase Learning Journey Timeline (Module 11) */
export const ALL_PHASES_TIMELINE = [
  { stage: SCENE_STAGES.COMMAND_CENTER,   name: 'Phase 1: Space Command Center', icon: '🚀', desc: 'Orbital mission control & satellite comms' },
  { stage: SCENE_STAGES.EARTH_VIEW,       name: 'Phase 2: Interactive Digital Earth', icon: '🌍', desc: 'Global disease heatmaps & flight tracking' },
  { stage: SCENE_STAGES.HISTORICAL_MUSEUM,name: 'Phase 3: Historical Pandemic Museum', icon: '🏛️', desc: 'Humanity’s fight against historic plagues' },
  { stage: SCENE_STAGES.HUMAN_BODY_JOURNEY,name: 'Phase 4: Human Body Journey', icon: '🫁', desc: 'Microscopic bloodstream & cellular defense' },
  { stage: SCENE_STAGES.AI_LABORATORY,    name: 'Phase 5: AI Biomedical Research Lab', icon: '🧬', desc: 'Genome sequencing & mRNA vaccine creation' },
  { stage: SCENE_STAGES.OUTBREAK_SIMULATOR,name: 'Phase 6: Global Outbreak Simulator', icon: '🚨', desc: 'WHO emergency operations & SEIR simulation' },
  { stage: SCENE_STAGES.BIOSHIELD_2050,   name: 'Phase 7: BioShield 2050 Smart City', icon: '🛡️', desc: 'Futuristic digital twin & autonomous drones' },
  { stage: SCENE_STAGES.CHALLENGE_PLATFORM,name: 'Phase 8: Crisis Challenge Platform', icon: '🏆', desc: 'Master challenges, quizzes & final diploma' },
  { stage: SCENE_STAGES.INTELLIGENCE_PLATFORM,name: 'Phase 9: Global Health Intelligence Platform', icon: '🌐', desc: 'Unified digital twin, knowledge graph & analytics' },
];

/** Outbreak Simulation Scenarios for Phase 6 */
export const OUTBREAK_SCENARIOS = [
  { id: 'covid',       name: 'COVID-Like Respiratory Outbreak', r0: 3.2, incubation: 5, severity: 'Moderate', hospitalization: 15, recoveryRate: 12, color: '#ff3860', desc: 'Airborne coronavirus strain spreading via respiratory droplets' },
  { id: 'ebola',       name: 'Ebola-Like Regional Hemorrhagic', r0: 1.8, incubation: 8, severity: 'High',     hospitalization: 40, recoveryRate: 21, color: '#ff9100', desc: 'Severe filovirus strain transmitted via direct contact' },
  { id: 'flu',         name: 'Pandemic Influenza A (H5N1)',    r0: 2.5, incubation: 2, severity: 'Moderate', hospitalization: 10, recoveryRate: 7,  color: '#00c8ff', desc: 'Rapidly mutating avian flu strain with airborne spread' },
  { id: 'novelX',      name: 'Novel Zoonotic Virus X',          r0: 4.5, incubation: 4, severity: 'Extreme',  hospitalization: 25, recoveryRate: 14, color: '#ff1744', desc: 'Highly contagious novel pathogen with zero baseline human immunity' },
  { id: 'superbug',   name: 'Drug-Resistant Superbug (AMR)',   r0: 2.1, incubation: 3, severity: 'Severe',   hospitalization: 30, recoveryRate: 18, color: '#7b2ff7', desc: 'Multidrug-resistant bacterial strain resistant to standard antibiotics' },
];

export const SIMULATION_SCENARIOS = OUTBREAK_SCENARIOS;

/** Strategic Player Action Policies (16 Decision Directives for Module 4) */
export const POLICY_DIRECTIVES = [
  { id: 'closeBorders',      title: 'Close International Borders',   r0Impact: -0.8, econImpact: -2.5, cost: 15, category: 'Travel',      desc: 'Halt international flights and maritime transit' },
  { id: 'openBorders',       title: 'Reopen Trade & Travel Borders', r0Impact: +0.6, econImpact: +3.0, cost: 0,  category: 'Travel',      desc: 'Restore international travel & boost global commerce' },
  { id: 'travelRestrict',    title: 'Inter-Regional Travel Lock',   r0Impact: -0.5, econImpact: -1.5, cost: 10, category: 'Travel',      desc: 'Restrict movement between domestic provinces' },
  { id: 'airportScreen',     title: 'Thermal Airport Screening',    r0Impact: -0.3, econImpact: -0.4, cost: 5,  category: 'Travel',      desc: 'Screen all incoming passengers at international terminals' },

  { id: 'massTesting',       title: 'Mass PCR Testing & Tracing',   r0Impact: -0.6, econImpact: -0.8, cost: 12, category: 'Testing',     desc: 'Deploy automated PCR testing centers & AI contact tracing' },
  { id: 'masks',             title: 'Mandatory Mask Mandate',        r0Impact: -0.4, econImpact: -0.2, cost: 4,  category: 'Prevention',  desc: 'Enforce N95 mask usage in public & indoor spaces' },
  { id: 'publicAwareness',   title: 'Public Health Broadcasts',      r0Impact: -0.3, econImpact: -0.1, cost: 3,  category: 'Prevention',  desc: 'Launch educational WHO TV, radio & social media campaigns' },
  { id: 'schoolClosure',     title: 'School & Venue Closures',       r0Impact: -0.7, econImpact: -2.0, cost: 14, category: 'Containment', desc: 'Close schools, universities, and mass entertainment venues' },

  { id: 'emergencyHospitals',title: 'Build Emergency Field Hospitals',r0Impact: 0.0,  econImpact: -1.2, cost: 18, category: 'Healthcare',  desc: 'Construct 500-bed modular surge facilities' },
  { id: 'icuBeds',           title: 'Increase ICU Bed Capacity',     r0Impact: 0.0,  econImpact: -0.8, cost: 12, category: 'Healthcare',  desc: 'Convert general wards into high-dependency ICU units' },
  { id: 'deployDoctors',     title: 'Deploy Medical Reserve Corps',  r0Impact: -0.2, econImpact: -0.5, cost: 8,  category: 'Healthcare',  desc: 'Mobilize military & volunteer doctors to epicenters' },
  { id: 'deployNurses',      title: 'Mobilize Critical Care Nurses', r0Impact: -0.2, econImpact: -0.4, cost: 6,  category: 'Healthcare',  desc: 'Staff intensive care units with specialized nursing teams' },

  { id: 'vaccineProd',       title: 'Scale Up Vaccine Production',   r0Impact: -0.2, econImpact: -1.0, cost: 20, category: 'Vaccination', desc: 'Expand bioreactor capacity for mass vaccine manufacturing' },
  { id: 'startVaccination',  title: 'Launch National Mass Vaccine',  r0Impact: -1.2, econImpact: -0.5, cost: 25, category: 'Vaccination', desc: 'Distribute vaccines to high-risk elderly & healthcare workers' },

  { id: 'emergencyFunding',  title: 'Release Emergency Funds',       r0Impact: 0.0,  econImpact: -3.0, cost: 30, category: 'Economics',   desc: 'Authorize $50B in emergency relief & healthcare subsidies' },
  { id: 'internationalAid',  title: 'Dispatch WHO Relief Aid',       r0Impact: -0.4, econImpact: -0.3, cost: 10, category: 'Aid',         desc: 'Airdrop medical PPE, oxygen & ventilators to low-income regions' },
];

/** Phase 7 BioShield 2050 Smart City Buildings (Modules 1 & 2 Digital Twin) */
export const BIOSHIELD_BUILDINGS = [
  { id: 'smarthospital',  name: 'Smart Hospital Complex',     type: 'Healthcare',  capacity: '92% Free', power: '99.8%', emergencyLevel: 'LOW', medicineStock: '98%', projects: 'AI Triage & Robotic Surgery', icon: '🏥', pos: [0, 0, 0] },
  { id: 'ailab',          name: 'AI Genomics Research Dome',   type: 'Research',    capacity: 'Optimal',  power: '100%',   emergencyLevel: 'NOMINAL', medicineStock: '100%', projects: 'Pan-Coronavirus mRNA Vaccine', icon: '🧬', pos: [-4, 0, -3] },
  { id: 'transporthub',   name: 'Bio-Secure Transit Hub',     type: 'Airport/Rail',capacity: '14,500/hr',power: '98.5%',  emergencyLevel: 'NOMINAL', medicineStock: '95%', projects: 'Thermal Scanning & UV Disinfection', icon: '🛫', pos: [4, 0, -3] },
  { id: 'vaccinecenter',  name: 'High-Throughput Vaccine Hub', type: 'Clinical',    capacity: '25k/Day',  power: '99.5%',  emergencyLevel: 'NOMINAL', medicineStock: '99%', projects: 'Autonomous Needleless Delivery', icon: '💉', pos: [-3, 0, 3] },
  { id: 'envtower',       name: 'Environmental Sensor Grid',  type: 'Surveillance',capacity: '100% Grid',power: '100%',   emergencyLevel: 'NOMINAL', medicineStock: 'N/A', projects: 'Airborne Pathogen Bio-Sampling', icon: '📡', pos: [3, 0, 3] },
];

/** Phase 7 Emergency Actions for Module 6 */
export const BIOSHIELD_ACTIONS = [
  { id: 'surgeHospital', title: 'Activate Surge Hospital Wings',   icon: '🏥', impact: 'Boosts bed capacity by +50%' },
  { id: 'droneDeliver',  title: 'Dispatch Drone Medicine Fleet',   icon: '🛸', impact: 'Cuts supply delivery time by 80%' },
  { id: 'mobileLab',     title: 'Deploy Mobile Bio-Analysis Units',icon: '🔬', impact: 'Accelerates field PCR diagnostics' },
  { id: 'massVaccine',   title: 'Initiate City-Wide Vaccine Drive',icon: '💉', impact: 'Increases immunity rate to 95%' },
  { id: 'publicAlert',   title: 'Broadcast Public Bio-Alerts',     icon: '📢', impact: 'Increases public safety compliance' },
  { id: 'schoolSafety',  title: 'Enable Air Scrubbing in Schools', icon: '🏫', impact: 'Eliminates indoor viral aerosols' },
];

/** Phase 7 Mission Challenges for Module 11 */
export const BIOSHIELD_CHALLENGES = [
  { id: 'vaccine95', title: 'Achieve 95% City Vaccination Rate', target: 95, current: 88, unit: '%' },
  { id: 'waitTime',  title: 'Reduce ER Wait Time to < 5 Minutes', target: 5, current: 8, unit: 'mins' },
  { id: 'awareness', title: 'Maintain Public Preparedness > 90%',target: 90, current: 92, unit: '%' },
  { id: 'stock',     title: 'Sustain Emergency Medicine Stock', target: 95, current: 98, unit: '%' },
];

/** Phase 7 Achievements for Module 12 */
export const BIOSHIELD_ACHIEVEMENTS = [
  { id: 'healthGuardian',    title: 'Health Guardian',       icon: '🛡️', desc: 'Maintained 95%+ BioShield health index' },
  { id: 'pandemicPreventer', title: 'Pandemic Preventer',    icon: '🔮', desc: 'Neutralized 100% of early viral outbreak signals' },
  { id: 'biosecurityExpert', title: 'Biosecurity Expert',    icon: '⚡', desc: 'Deployed autonomous drone & robotic fleets' },
  { id: 'futureScientist',   title: 'Future Scientist',       icon: '🔬', desc: 'Completed all 7 AI Laboratory research pipelines' },
  { id: 'globalLeader',      title: 'Global Health Leader',   icon: '🌐', desc: 'Established international vaccine sharing partnerships' },
];

/** 6 Global Geographical Regions for Resource Allocation (Module 5) */
export const OUTBREAK_REGIONS = [
  { id: 'asia',          name: 'Asia-Pacific',    population: 4600000000, flag: '🌏', risk: 'Red',    doctors: 1200000, nurses: 2500000, beds: 8000000, icu: 450000, vaccines: 15000000, funds: 85 },
  { id: 'europe',        name: 'Europe',          population: 740000000,  flag: '🇪🇺', risk: 'Yellow', doctors: 950000,  nurses: 1800000, beds: 3500000, icu: 280000, vaccines: 45000000, funds: 120 },
  { id: 'africa',        name: 'Africa',          population: 1300000000, flag: '🌍', risk: 'Orange', doctors: 320000,  nurses: 650000,  beds: 1200000, icu: 85000,  vaccines: 5000000,  funds: 30 },
  { id: 'northamerica',  name: 'North America',   population: 590000000,  flag: '🌎', risk: 'Yellow', doctors: 820000,  nurses: 1600000, beds: 2800000, icu: 310000, vaccines: 50000000, funds: 150 },
  { id: 'latinamerica',  name: 'Latin America',   population: 650000000,  flag: '💃', risk: 'Orange', doctors: 450000,  nurses: 900000,  beds: 1800000, icu: 140000, vaccines: 12000000, funds: 45 },
  { id: 'middleeast',    name: 'Middle East',     population: 450000000,  flag: '🕌', risk: 'Green',  doctors: 280000,  nurses: 520000,  beds: 1100000, icu: 95000,  vaccines: 8000000,  funds: 60 },
];

/** Mission Objectives for Module 11 */
export const MISSION_OBJECTIVES = [
  { id: 'deathsTarget',   title: 'Keep Global Fatalities Under 2.5 Million', target: 2500000 },
  { id: 'icuCapacity',    title: 'Maintain Hospital ICU Occupancy Below 85%', target: 85 },
  { id: 'vaccineCoverage',title: 'Achieve 70% Global Immunization',          target: 70 },
  { id: 'publicConfidence',title: 'Sustain Global Health Index > 75%',      target: 75 },
];

/** Portal definitions for the Command Center hub */
export const PORTALS = [
  { id: 'mission-control',  label: 'Mission Control',       active: true,  angle: 0 },
  { id: 'timeline',         label: 'Historical Timeline',   active: true,  angle: 60 },
  { id: 'human-body',       label: 'Human Body Journey',    active: true,  angle: 180 },
  { id: 'laboratory',       label: 'AI Research Lab',       active: true,  angle: 120 },
  { id: 'outbreak-sim',     label: 'Outbreak Simulator',    active: true,  angle: 240 },
  { id: 'bioshield',        label: 'BioShield 2050 City',   active: true,  angle: 300 },
];

/** Dashboard panel data (animated numbers) */
export const DASHBOARD_DATA = {
  earthStatus:    { label: 'Earth Status',          value: '98.7%', status: 'nominal',  unit: 'HEALTH' },
  satellites:     { label: 'Satellites Online',     value: '247',   status: 'nominal',  unit: 'UNITS' },
  globalHealth:   { label: 'Global Health Index',   value: '74.2',  status: 'warning',  unit: 'INDEX' },
  research:       { label: 'Research Progress',     value: '62%',   status: 'nominal',  unit: 'COMPLETE' },
  network:        { label: 'Comm Network',          value: '99.9%', status: 'nominal',  unit: 'UPTIME' },
  power:          { label: 'Station Power',         value: '94.1%', status: 'nominal',  unit: 'CAPACITY' },
};

/** Holographic color palette */
export const COLORS = {
  bg:         0x010409,
  blue:       0x00c8ff,
  blueDim:    0x0077aa,
  blueGlow:   0x0044aa,
  accent:     0x7b2ff7,
  success:    0x00ff9d,
  warning:    0xffb700,
  danger:     0xff3860,
  white:      0xffffff,
  starWhite:  0xc8e6ff,
};

/** Earth geometry */
export const EARTH_RADIUS = 2;

/** Station position in world space */
export const STATION_POS = [0, 0, -10];

/** Camera positions per stage */
export const CAMERA_POSITIONS = {
  [SCENE_STAGES.LOADING]:          { pos: [0, 0, 5],   target: [0, 0, 0] },
  [SCENE_STAGES.CINEMATIC_INTRO]:  { pos: [0, 2, 6],   target: [0, 0, 0] },
  [SCENE_STAGES.ROCKET_LAUNCH]:    { pos: [3, 1.5, 8], target: [0, 2, 0] },
  [SCENE_STAGES.SPACE_FLIGHT]:     { pos: [0, 2, 12],  target: [0, 0, 0] },
  [SCENE_STAGES.ORBITAL_STATION]:  { pos: [6, 3, -5],  target: [0, 0, -10] },
  [SCENE_STAGES.COMMAND_CENTER]:   { pos: [0, 1, 2],   target: [0, 0, 0] },
  [SCENE_STAGES.MISSION_CONTROL]:  { pos: [0, 0.5, 0], target: [0, 0, -3] },
  [SCENE_STAGES.BIOSHIELD_2050]:   { pos: [0, 4, 10],  target: [0, 0, 0] },
  [SCENE_STAGES.CHALLENGE_PLATFORM]:{ pos: [0, 3, 9],  target: [0, 0, 0] },
  [SCENE_STAGES.INTELLIGENCE_PLATFORM]:{ pos: [0, 4, 11], target: [0, 0, 0] },
};

/** Phase 9 Digital Twin Layers (Module 2) */
export const DIGITAL_TWIN_LAYERS = [
  { id: 'climate',        name: 'Climate & Temperature',   icon: '🌡️', color: '#ff9100', status: 'ACTIVE',  desc: 'Global temperature anomalies & humidity transport vectors.' },
  { id: 'population',     name: 'Population Density',      icon: '👥', color: '#00c8ff', status: 'ACTIVE',  desc: 'Urban density clusters & international transit corridors.' },
  { id: 'healthcare',     name: 'Healthcare Capacity',    icon: '🏥', color: '#00ff9d', status: 'ACTIVE',  desc: 'ICU occupancy strain & emergency field bed availability.' },
  { id: 'vaccination',    name: 'Vaccination Coverage',    icon: '💉', color: '#7b2ff7', status: 'ACTIVE',  desc: 'Real-time global vaccine administration & immunity rates.' },
  { id: 'transportation', name: 'Global Transport Grid',  icon: '✈️', color: '#00e5ff', status: 'ACTIVE',  desc: 'Live airline routes, maritime cargo, and high-speed rail.' },
  { id: 'hospitals',      name: 'Smart Hospitals',         icon: '🏢', color: '#ff3860', status: 'ACTIVE',  desc: 'Automated 3D medical centers & ICU robotics hubs.' },
  { id: 'research',       name: 'Research Laboratories',   icon: '🔬', color: '#ffb700', status: 'ACTIVE',  desc: 'BSL-4 cleanrooms, mRNA synthesis, & genomic supercomputers.' },
  { id: 'history',        name: 'Disease History Map',     icon: '📜', color: '#ff2a85', status: 'HISTORIC',desc: 'Geographic epicenters of past historic pandemics.' },
  { id: 'preparedness',   name: 'Preparedness Index',      icon: '🛡️', color: '#00ff9d', status: 'COMPUTED',desc: 'Composite biosecurity preparedness score per nation.' },
];

/** Phase 9 Pandemic Knowledge Graph Nodes (Module 3) */
export const KNOWLEDGE_GRAPH_NODES = [
  { id: 'blackdeath', label: 'Black Death',       type: 'Pandemic', cat: 'history', color: '#ff3860' },
  { id: 'smallpox',   label: 'Smallpox',          type: 'Pandemic', cat: 'history', color: '#ff9100' },
  { id: 'spanishflu', label: '1918 Spanish Flu',  type: 'Pandemic', cat: 'history', color: '#ffb700' },
  { id: 'covid19',    label: 'COVID-19',          type: 'Pandemic', cat: 'history', color: '#7b2ff7' },
  { id: 'pestis',     label: 'Yersinia Pestis',   type: 'Bacteria', cat: 'pathogen',color: '#ff3860' },
  { id: 'sarscov2',   label: 'SARS-CoV-2',        type: 'Virus',    cat: 'pathogen',color: '#00c8ff' },
  { id: 'h1n1',       label: 'H1N1 Influenza',    type: 'Virus',    cat: 'pathogen',color: '#00ff9d' },
  { id: 'mrna',       label: 'mRNA Vaccine',      type: 'Discovery',cat: 'vaccine', color: '#00e5ff' },
  { id: 'pcr',        label: 'PCR Diagnostics',   type: 'Discovery',cat: 'tech',    color: '#00c8ff' },
  { id: 'who',        label: 'WHO Intelligence',  type: 'Alliance', cat: 'org',     color: '#00ff9d' },
  { id: 'bioshield',  label: 'BioShield 2050',    type: 'Prevention',cat:'future', color: '#7b2ff7' },
];

export const KNOWLEDGE_GRAPH_EDGES = [
  { from: 'blackdeath', to: 'pestis', label: 'Causative Agent' },
  { from: 'covid19', to: 'sarscov2', label: 'Causative Agent' },
  { from: 'covid19', to: 'mrna', label: 'Vaccine Breakthrough' },
  { from: 'covid19', to: 'pcr', label: 'Diagnostic Testing' },
  { from: 'spanishflu', to: 'h1n1', label: 'Viral Subtype' },
  { from: 'who', to: 'covid19', label: 'Global Surveillance' },
  { from: 'who', to: 'bioshield', label: 'Future Strategy' },
  { from: 'mrna', to: 'bioshield', label: 'Nanoparticle Tech' },
];

/** Phase 9 Research Archive Reports (Module 5 & 11) */
export const RESEARCH_ARCHIVE_REPORTS = [
  { id: 'rep1', title: 'Black Death Plague Isolation Protocol (1347)', category: 'History', date: '1347-10-15', score: '98/100', summary: 'Analysis of Venetian maritime quarantine and isolation effectiveness.' },
  { id: 'rep2', title: '1918 Spanish Influenza Transmission Study', category: 'Viral', date: '1918-11-11', score: '94/100', summary: 'Wartime troop movement & pulmonary aerosol spread dynamics.' },
  { id: 'rep3', title: 'SARS-CoV-2 Spike Protein Genomic Sequence', category: 'Genomics', date: '2020-01-12', score: '99/100', summary: '3D structural resolution of ACE2 receptor binding domain.' },
  { id: 'rep4', title: 'Phase 5 AI Lab mRNA Vaccine Synthesis', category: 'Laboratory', date: '2026-07-20', score: '100/100', summary: 'High-throughput lipid nanoparticle encapsulation & bioprocessing.' },
  { id: 'rep5', title: 'Phase 6 WHO Emergency Outbreak Simulation', category: 'Simulation', date: '2026-07-22', score: '96/100', summary: 'SEIR epidemiological curve flattening & ICU bed allocation.' },
  { id: 'rep6', title: 'Phase 7 BioShield 2050 Autonomous Telemetry', category: 'Future City', date: '2050-01-01', score: '98/100', summary: 'Medical drone logistics, air scrubbing, & digital twin telemetry.' },
  { id: 'rep7', title: 'Phase 8 Global Crisis Challenge Master Diploma', category: 'Certification', date: '2026-07-26', score: '980 PTS', summary: 'Official Global Pandemic Preparedness Specialist Diploma.' },
];

/** Phase 9 Learning Library Glossary & Encyclopedia (Module 8) */
export const LEARNING_LIBRARY_ENTRIES = [
  { id: 'r0', term: 'Basic Reproduction Number (R0)', category: 'Public Health', desc: 'The average number of secondary infections produced by one infected individual in a fully susceptible population.' },
  { id: 'mrna', term: 'mRNA Vaccines', category: 'Vaccines', desc: 'Vaccines that introduce synthetic messenger RNA encoding viral antigens to instruct host cells to trigger immune memory without live pathogen.' },
  { id: 'pcr', term: 'Polymerase Chain Reaction (PCR)', category: 'Diagnostics', desc: 'A molecular technique that amplifies tiny segments of viral DNA/RNA for rapid, highly accurate diagnosis.' },
  { id: 'herd', term: 'Herd Immunity', category: 'Epidemiology', desc: 'Resistance to the spread of a contagious disease within a population that results if a sufficiently high proportion of individuals are immune.' },
  { id: 'cytokine', term: 'Cytokine Storm', category: 'Immune System', desc: 'A severe immune reaction in which the body releases too many cytokines into the blood too quickly, damaging healthy tissue.' },
  { id: 'zoonotic', term: 'Zoonotic Spillover', category: 'Pathogens', desc: 'The transmission of a pathogen from an animal host to a human host, often originating in bats, birds, or rodents.' },
];

/** Timing durations (milliseconds) */
export const DURATIONS = {
  loading:         3000,
  intro:           4000,
  rocketLaunch:    6000,
  spaceFlight:     5000,
  docking:         4000,
  cameraTransition:2000,
  shrink:          3200,
};

/** Research Lab Workstations for Phase 5 */
export const LAB_WORKSTATIONS = [
  { id: 'analysis',     name: 'Pathogen Analysis',     desc: '3D Protein Slicing & AI Bio-Reports', icon: '🔬', color: '#00c8ff' },
  { id: 'sequencing',   name: 'Genome Sequencing',     desc: 'DNA Base Pair Mapping & Mutation Editor', icon: '🧬', color: '#00ff9d' },
  { id: 'microscope',   name: 'Digital Microscope',    desc: '100x – 1,000,000x Lens Inspection', icon: '🔍', color: '#7b2ff7' },
  { id: 'diagnostics',  name: 'AI Diagnostics',        desc: 'Automated Sample Pathology Detector', icon: '🤖', color: '#ffb700' },
  { id: 'drugdiscovery',name: 'Drug Discovery',        desc: '3D Molecular Docking & Binding Lab', icon: '🧪', color: '#ff3860' },
  { id: 'vaccine',      name: 'Vaccine Pipeline',      desc: '9-Stage Creation & Bioreactor Facility', icon: '💉', color: '#00e5ff' },
  { id: 'dashboard',    name: 'Global Dashboard',      desc: 'WHO Collaboration & Trial Monitoring', icon: '📊', color: '#ff9100' },
];

/** Organ System Environments for Phase 4 */
export const ORGAN_SYSTEMS = [
  { id: 'bloodstream', name: 'Bloodstream',           desc: 'Circulatory Vascular Tunnel',     scale: '10 µm', color: '#ff1744', icon: '🩸' },
  { id: 'lungs',       name: 'Respiratory System',   desc: 'Pulmonary Alveoli & Air Sacs',     scale: '5 µm',  color: '#00e5ff', icon: '🫁' },
  { id: 'heart',       name: 'Cardiovascular Heart',   desc: 'Myocardial Tissue & Arteries',    scale: '20 µm', color: '#ff3860', icon: '🫀' },
  { id: 'brain',       name: 'Central Nervous System', desc: 'Cerebral Neurons & Synapses',    scale: '2 µm',  color: '#7b2ff7', icon: '🧠' },
  { id: 'liver',       name: 'Hepatic System',         desc: 'Liver Lobules & Detox Filter',    scale: '15 µm', color: '#ff9100', icon: '🧪' },
  { id: 'kidneys',     name: 'Renal Nephrons',         desc: 'Glomerular Filtration System',    scale: '8 µm',  color: '#ffb700', icon: '💧' },
  { id: 'lymphatic',   name: 'Lymphatic System',       desc: 'Lymph Nodes & T-Cell Reserve',    scale: '5 µm',  color: '#00ff9d', icon: '🛡️' },
  { id: 'immune',      name: 'Immune Defense Core',    desc: 'Bone Marrow & Antibody Factory',  scale: '1 µm',  color: '#00c8ff', icon: '⚔️' },
];

/** Microscopic View Modes */
export const BODY_VIEW_MODES = [
  { id: 'bloodstream', label: 'BLOODSTREAM NAVIGATOR', icon: '🩸' },
  { id: 'cellular',    label: 'HOST CELL WORLD',       icon: '🔬' },
  { id: 'infection',   label: 'INFECTION SIMULATION',  icon: '☣️' },
  { id: 'immune',      label: 'IMMUNE SYSTEM DEFENSE', icon: '🛡️' },
  { id: 'vaccine',     label: 'VACCINE EXPLAINER',     icon: '💉' },
  { id: 'genetics',    label: 'DNA & GENETICS LAB',    icon: '🧬' },
];
